In [1]:
import tensorflow as tf
import numpy as np
tf.enable_eager_execution()

In [2]:
src_dlatents = tf.constant([[[0, 1, 2]] * 14, [[3, 4, 5]] * 14])
dst_dlatents = tf.constant([[[6, 7, 8]] * 14, [[9, 10, 11]] * 14])

In [3]:
print(src_dlatents)
print(dst_dlatents)

tf.Tensor(
[[[0 1 2]
  [0 1 2]
  [0 1 2]
  [0 1 2]
  [0 1 2]
  [0 1 2]
  [0 1 2]
  [0 1 2]
  [0 1 2]
  [0 1 2]
  [0 1 2]
  [0 1 2]
  [0 1 2]
  [0 1 2]]

 [[3 4 5]
  [3 4 5]
  [3 4 5]
  [3 4 5]
  [3 4 5]
  [3 4 5]
  [3 4 5]
  [3 4 5]
  [3 4 5]
  [3 4 5]
  [3 4 5]
  [3 4 5]
  [3 4 5]
  [3 4 5]]], shape=(2, 14, 3), dtype=int32)
tf.Tensor(
[[[ 6  7  8]
  [ 6  7  8]
  [ 6  7  8]
  [ 6  7  8]
  [ 6  7  8]
  [ 6  7  8]
  [ 6  7  8]
  [ 6  7  8]
  [ 6  7  8]
  [ 6  7  8]
  [ 6  7  8]
  [ 6  7  8]
  [ 6  7  8]
  [ 6  7  8]]

 [[ 9 10 11]
  [ 9 10 11]
  [ 9 10 11]
  [ 9 10 11]
  [ 9 10 11]
  [ 9 10 11]
  [ 9 10 11]
  [ 9 10 11]
  [ 9 10 11]
  [ 9 10 11]
  [ 9 10 11]
  [ 9 10 11]
  [ 9 10 11]
  [ 9 10 11]]], shape=(2, 14, 3), dtype=int32)


In [4]:
mixed_dlatents = []
for i in range(0, src_dlatents.get_shape().as_list()[0]):
    middle_dlatent = tf.concat([tf.gather(src_dlatents[i], range(0, 4)), tf.gather(dst_dlatents[i], range(4, 8)), tf.gather(src_dlatents[i], range(8, 14))], 0)
    fine_dlatent = tf.concat([tf.gather(src_dlatents[i], range(0, 8)), tf.gather(dst_dlatents[i], range(8, 14))], 0)
    mixed_dlatents.append(middle_dlatent)
    mixed_dlatents.append(fine_dlatent)
mixed_dlatents = tf.stack(mixed_dlatents)
print(mixed_dlatents)


tf.Tensor(
[[[ 0  1  2]
  [ 0  1  2]
  [ 0  1  2]
  [ 0  1  2]
  [ 6  7  8]
  [ 6  7  8]
  [ 6  7  8]
  [ 6  7  8]
  [ 0  1  2]
  [ 0  1  2]
  [ 0  1  2]
  [ 0  1  2]
  [ 0  1  2]
  [ 0  1  2]]

 [[ 0  1  2]
  [ 0  1  2]
  [ 0  1  2]
  [ 0  1  2]
  [ 0  1  2]
  [ 0  1  2]
  [ 0  1  2]
  [ 0  1  2]
  [ 6  7  8]
  [ 6  7  8]
  [ 6  7  8]
  [ 6  7  8]
  [ 6  7  8]
  [ 6  7  8]]

 [[ 3  4  5]
  [ 3  4  5]
  [ 3  4  5]
  [ 3  4  5]
  [ 9 10 11]
  [ 9 10 11]
  [ 9 10 11]
  [ 9 10 11]
  [ 3  4  5]
  [ 3  4  5]
  [ 3  4  5]
  [ 3  4  5]
  [ 3  4  5]
  [ 3  4  5]]

 [[ 3  4  5]
  [ 3  4  5]
  [ 3  4  5]
  [ 3  4  5]
  [ 3  4  5]
  [ 3  4  5]
  [ 3  4  5]
  [ 3  4  5]
  [ 9 10 11]
  [ 9 10 11]
  [ 9 10 11]
  [ 9 10 11]
  [ 9 10 11]
  [ 9 10 11]]], shape=(4, 14, 3), dtype=int32)


In [5]:
def mix_middle(x):
    return tf.concat([tf.gather(x[0], list(range(0, 4))), tf.gather(x[1], list(range(4, 8))),
                      tf.gather(x[0], list(range(8, 14)))], 0)

def mix_fine(x):
    return tf.concat([tf.gather(x[0], list(range(0, 8))), tf.gather(x[1], list(range(8, 14)))], 0)

def mix_dlatents(src_dlatents, dst_dlatents):
    stacked_dlatents = tf.stack([src_dlatents, dst_dlatents], axis=1)
    middle_dlatents = tf.map_fn(mix_middle, stacked_dlatents)
    fine_dlatents = tf.map_fn(mix_fine, stacked_dlatents)
    return tf.concat([middle_dlatents, fine_dlatents], 0)

print(mix_dlatents(src_dlatents, dst_dlatents))

tf.Tensor(
[[[ 0  1  2]
  [ 0  1  2]
  [ 0  1  2]
  [ 0  1  2]
  [ 6  7  8]
  [ 6  7  8]
  [ 6  7  8]
  [ 6  7  8]
  [ 0  1  2]
  [ 0  1  2]
  [ 0  1  2]
  [ 0  1  2]
  [ 0  1  2]
  [ 0  1  2]]

 [[ 3  4  5]
  [ 3  4  5]
  [ 3  4  5]
  [ 3  4  5]
  [ 9 10 11]
  [ 9 10 11]
  [ 9 10 11]
  [ 9 10 11]
  [ 3  4  5]
  [ 3  4  5]
  [ 3  4  5]
  [ 3  4  5]
  [ 3  4  5]
  [ 3  4  5]]

 [[ 0  1  2]
  [ 0  1  2]
  [ 0  1  2]
  [ 0  1  2]
  [ 0  1  2]
  [ 0  1  2]
  [ 0  1  2]
  [ 0  1  2]
  [ 6  7  8]
  [ 6  7  8]
  [ 6  7  8]
  [ 6  7  8]
  [ 6  7  8]
  [ 6  7  8]]

 [[ 3  4  5]
  [ 3  4  5]
  [ 3  4  5]
  [ 3  4  5]
  [ 3  4  5]
  [ 3  4  5]
  [ 3  4  5]
  [ 3  4  5]
  [ 9 10 11]
  [ 9 10 11]
  [ 9 10 11]
  [ 9 10 11]
  [ 9 10 11]
  [ 9 10 11]]], shape=(4, 14, 3), dtype=int32)


In [6]:
a = tf.constant([1, 2, 3])
b = tf.constant([1, 2])
print(a)
print(b)
c = tf.add(a, b)
print(c)
c

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)


InvalidArgumentError: Incompatible shapes: [3] vs. [2] [Op:Add]